import "../globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";

export const metadata = {
  title: "Vels Vidyashram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />

        <main className="relative z-0">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
