import "../globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import ScrollToTop from "./components/ScrollToTop";
import Modal from "./layout/modals";

export const metadata = {
  title: "Vels Vidyashram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
         <Modal />
        <main className="relative z-0">
          {children}
        </main>
        <ScrollToTop />

        <Footer />
      </body>
    </html>
  );
}
